Bookers/config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  get 'posts/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'root#top'

  post 'posts' => 'posts#create'

  get 'posts' => 'posts#index'

  get 'posts/:id' => 'posts#show', as: 'post'

  get 'posts/:id/edit' => 'posts#edit', as: 'edit_post'

  patch 'posts/:id' => 'posts#update', as: 'update_post'

  delete 'posts/:id' => 'posts#destroy', as: 'destroy_post'

end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/post.rb
class Post < ApplicationRecord
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Post.new
  end

  def create
         post = Post.new(post_params)
         if post.save
         	flash[:notice] = "Book was successfully created."
         redirect_to post_path(post.id)
     else
     	render action: :new
     end
  end

  def update
      @post = Post.find(params[:id])
      @post.update(post_params)
      redirect_to @post
end

  def index
      @posts = Post.all
      @post = Post.new
  end

  def show
        @post = Post.find(params[:id])
  end

  def edit
        @post = Post.find(params[:id])
  end

  def update
        post = Post.find(params[:id])
        if post.update(post_params)
        	flash[:notice] = "Book was successfully updated."
        redirect_to post_path(post.id)
    else
    	render action: :new
    end
  end

  def destroy
        post = Post.find(params[:id])
        if post.destroy
        	flash[:notice] = "Book was successfully destroyed."
        redirect_to posts_path
    else
    	render action: :new
    end
  end



  private

    def post_params
        params.require(:post).permit(:title, :body)
    end
end

Bookers/app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
	end
end

Bookers/app/controllers/top_controller.rb
class TopController < ApplicationController

	def index
	end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/posts_helper.rb
module PostsHelper
end

Bookers/app/helpers/root_helper.rb
module RootHelper
end

Bookers/app/helpers/top_helper.rb
module TopHelper
end

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Bookers/app/views/posts/edit.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h1>Editing Book</h1>
<%= form_for(@post) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title, class: "book_title" %>
    <h4>Body</h4>
    <%= f.text_area :body, class: "book_body" %>
    <%= f.submit 'Update Book' %>
<% end %>
<%= link_to 'Show', post_path, class: "show_#{@post.id}" %>
<%= link_to 'Back', posts_path, class: "back" %>

Bookers/app/views/posts/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h1>Books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= link_to 'Show', post_path(post), class: "show_#{post.id}" %></td>
      <td><%= link_to 'Edit', edit_post_path(post), class: "edit_#{post.id}" %></td>
      <td><%= link_to 'Destroy', post_path(post), class: "destroy_#{post.id}",
                method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<h1>New book</h1>
<!-- form_for部分 -->
<%= form_for(@post) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title, class: "book_title" %>

    <h4>Body</h4>
    <%= f.text_area :body, class: "book_body" %>

    <%= f.submit 'Create Book' %>

<% end %>

Bookers/app/views/posts/new.html.erb
<h1>New book</h1>
<!-- form_for部分 -->
<%= form_for(@post) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>

Bookers/app/views/posts/show.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>

<h2>Title</h2>
<p><%= @post.title %></p>
<h2>Body</h2>
<p><%= @post.body %></p>


<%= link_to "Edit", edit_post_path, class: "edit_#{@post.id}" %>
<%= link_to 'Back', posts_path, class: "back" %>

Bookers/app/views/root/top.html.erb
<h1>ようこそ
<strong>Bookers</strong> へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to 'Start', controller:"posts" %>

Bookers/app/views/top/index.html.erb
<h1>ようこそ
<strong>Bookers</strong> へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to 'Start', controller:"posts" %>